apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-test
  name: devops-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-test
  strategy:
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/os=linux"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: devops-test
      initContainers:
      - name: db-checker
        image: mysql
        command: ['sh', '-c', 'until mysqladmin ping -h"my-release-mysql" --silent; do echo "Waiting for data base ready"; sleep 2; done;']
      containers:
      - image: devops-test
        imagePullPolicy: IfNotPresent
        name: devops-test
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-root-password
                name: my-release-mysql
          - name: NODE_NAME
            valueFrom:
              configMapKeyRef:
                name: node-name-config  
                key: NODE_NAME  
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 1G
          limits:
            cpu: 2
            memory: 2G