apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - newName: devops-test
    newTag: v1
    name: devops-test
namespace: default
