apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devops-test
  name: devops-test
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app: devops-test
  type: LoadBalancer
